---
title: "NN5 dataset"
authors: "Mahdi", "Mehrdad", "Sasan"
date: "June 28, 2018"
output: html_document
---

```{r}
library(TStools)
library(tscompdata)
library(ggplot2)
library(tidyverse)
library(imputeTS)
library(psych)
library(thief)
library(forecTheta)
library(data.table)
library(TSstudio)
```

# Data wrangling

```{r}
# lets first take alook at some our time series 
autoplot(mstl(nn5[[1]]))
autoplot(mstl(nn5[[10]]))
autoplot(mstl(nn5[[20]])) # so we have weekly and yearly seasonality as we expected

unlist(nn5) %>% summary() #1677 internal missing values for now I am not deleting them.

result <- data.frame(series = names(nn5), lamda = NA_real_ )
result_35 <- data.frame(series = names(nn5), lamda = NA_real_ )
result_56 <- data.frame(series = names(nn5), lamda = NA_real_ )

# rolling origin and NA handler function

rolling_ori <- function(x,h,n){
  y <- list()
  RO <- list()
  for (i in seq_len(n)){
    train_len <- (791-h-i+1)
    y <- as.numeric(na.mean(x, option = "mean"))
    RO[[i]] <- ts(y[(1:(train_len))], frequency = 7, start = c(1,1))
    RO[[i+n]] <- y[(train_len+1):(791-i+1)] # e.g for n = 3,  1-3 is training data whereas 4-6 is test
  }
  return(RO)
}

# we also need msts for tbats

rolling_ori_msts <- function(x,h,n){
  y <- list()
  RO <- list()
  for (i in seq_len(n)){
    train_len <- (791-h-i+1)
    y <- na.mean(x, option = "mean")
    RO[[i]] <- msts(y[(1:(train_len))], seasonal.periods = c(7, 365)) 
    RO[[i+n]] <- y[(train_len+1):(791-i+1)] # e.g for n = 3,  1-3 is training data whereas 4-6 is test
  }
  return(RO)
}

#lets create our new data

set.seed(2018)



# before our first forecast lets see if we need BOX-COX transformation
result <- mutate(result, lamda = sapply(nn5,BoxCox.lambda)) 
result_35 <- mutate(result_35, lamda = sapply(nn5,BoxCox.lambda)) 
result_56 <- mutate(result_56, lamda = sapply(nn5,BoxCox.lambda)) 

# error fun, x is forecast and y is known value

# mean absolute error 
MAE <- function(x,y){ 
  return(mean(abs(as.numeric(x-y))))
}

# lets create RelAvgRMSE :

RMSE <- function(x,y){
  return(sqrt(mean(as.numeric((x-y))^2)))
}

RelAvgRMSE <- function(x,z){
  return(geometric.mean(x/z))  # geommean is on the 111 time series, z is the RMSE of naive forecast
}


sMAPE <- function(x,y){
  return(2*mean(abs(as.numeric(x-y))/(abs(as.numeric(x))+abs(as.numeric(y)))))   #Hyndman sMAPE
}

```

# lets start forecasting

# 1.Snaive
```{r}
# since from now on we will need MAE of Snaive for MASE of our future models we compute it here
pred2 <- function(z,h,n){
  A <- data.frame( series = names(nn5),Snaive_smape1 = NA_real_, Snaive_mase1 = NA_real_, Snaive_smape2 =
                     NA_real_, Snaive_mase2 = NA_real_,
                  Snaive_smape3 = NA_real_, Snaive_mase3 = NA_real_, mae1 = NA_real_, mae2 = NA_real_,
                  mae3 = NA_real_)
#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
    fit <- snaive(x[[i]], h = h)
    A[j,2*i] <- sMAPE(fit$mean, x[[i+n]])
    mae <- MAE(fit$mean, x[[i+n]])
    A[j,2*i+1] <- MASE(fit$mean, x[[i+n]], scale = mae ) #MASE from smooth package
    A[j,2*n+1+i] <- mae  # MAE for future computations
    }
  }
  A <- mutate(group_by(A, series), Snaive_smape = (( Snaive_smape1 + Snaive_smape2 + Snaive_smape3)/3))
  A <- mutate(group_by(A, series), Snaive_mase = (( Snaive_mase1 + Snaive_mase2 + Snaive_mase3)/3)) # mean as
  # representer
  
  return(A[,c( "series", "Snaive_smape", "Snaive_mase", "mae1", "mae2", "mae3")])
}





```


# 2.Naive
```{r}
#lets define the rolling origin function to divide the data to test and train sets with appropriate origins and
#horizons

pred1 <- function(z,h,n){
  A <- data.frame( series = names(nn5),naive_smape1 = NA_real_, naive_mase1 = NA_real_, naive_smape2 =
                     NA_real_,naive_mase2 = NA_real_,
                  naive_smape3 = NA_real_, naive_mase3 = NA_real_, RMSE1 = NA_real_, RMSE2 = NA_real_,
                  RMSE3 = NA_real_)
#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
    fit <- naive(x[[i]], h = h)
    A[j,2*i] <- sMAPE(fit$mean, x[[i+n]])
    A[j,2*i+1] <- MASE(fit$mean, x[[i+n]], scale = df.mae[j,i+1] ) #MASE from smooth package
    A[j,2*n+1+i] <- RMSE(fit$mean, x[[i+n]])
    }
  }
  A <- mutate(group_by(A, series), naive_smape = (( naive_smape1 + naive_smape2 + naive_smape3)/3))
  A <- mutate(group_by(A, series), naive_mase = (( naive_mase1 + naive_mase2 + naive_mase3)/3)) # mean as
  # representer
  
  return(A[,c( "series", "naive_smape", "naive_mase","RMSE1", "RMSE2", "RMSE3")])
}



```


# 3.ETS
```{r}
# first we need to define our MASE function


pred3 <- function(z,h,n){
  A <- data.frame( series = names(nn5),ZZZ_smape1 = NA_real_, ZZZ_mase1 = NA_real_, ZZZ_smape2 =
                     NA_real_, ZZZ_mase2 = NA_real_,
                  ZZZ_smape3 = NA_real_, ZZZ_mase3 = NA_real_, ZZZ_RMSE1 =NA_real_,ZZZ_RMSE2 =
                    NA_real_,
                  ZZZ_RMSE3 = NA_real_, ZZZ_RelAvgRMSE = NA_real_)

#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
    pred <- es(x[[i]], model = "ZZZ", h = h)$forecast
    A[j,2*i] <- sMAPE(pred, x[[i+n]])
    A[j,2*i+1] <- MASE(pred, x[[i+n]], scale = df.mae[j,i+1])
    A[j,2*n+1+i] <- RMSE(pred, x[[i+n]])
    }
    
  }
  
  A <- mutate(group_by(A, series), ZZZ_smape = (( ZZZ_smape1 + ZZZ_smape2 + ZZZ_smape3)/3))
  A <- mutate(group_by(A, series), ZZZ_mase = (( ZZZ_mase1 + ZZZ_mase2 + ZZZ_mase3)/3)) # mean as representer
  A[(1:111),11] <- ((RelAvgRMSE(A["ZZZ_RMSE1"],df.RMSE[,2]) + (RelAvgRMSE((A["ZZZ_RMSE2"]), df.RMSE[,3]) +
                                                 (RelAvgRMSE((A["ZZZ_RMSE3"]), df.RMSE[,4]))/3)))
    
  return(A[,c( "series", "ZZZ_smape", "ZZZ_mase", "ZZZ_RelAvgRMSE")])
}



```

# 4.Simple Moving Average

```{r}

pred4 <- function(z,h,n){
  A <- data.frame( series = names(nn5),SMA_smape1 = NA_real_, SMA_mase1 = NA_real_, SMA_smape2 =
                     NA_real_, SMA_mase2 = NA_real_,
                  SMA_smape3 = NA_real_, SMA_mase3 = NA_real_, SMA_RMSE1 =NA_real_,SMA_RMSE2 = NA_real_,
                  SMA_RMSE3 = NA_real_, SMA_RelAvgRMSE = NA_real_)

#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
    fit <- sma(x[[i]], h = h ) 
    pred <- fit$forecast
    A[j,2*i] <- sMAPE(pred, x[[i+n]])
    A[j,2*i+1] <- MASE(pred, x[[i+n]], scale = df.mae[j,i+1])
    A[j,2*n+1+i] <- RMSE(pred, x[[i+n]])
    }
    
  }
  
  A <- mutate(group_by(A, series), SMA_smape = (( SMA_smape1 + SMA_smape2 + SMA_smape3)/3))
  A <- mutate(group_by(A, series), SMA_mase = (( SMA_mase1 + SMA_mase2 + SMA_mase3)/3)) # mean as representer
  A[(1:111),11] <- ((RelAvgRMSE(A["SMA_RMSE1"],df.RMSE[,2]) + (RelAvgRMSE((A["SMA_RMSE2"]), df.RMSE[,3]) +
                                                 (RelAvgRMSE((A["SMA_RMSE3"]), df.RMSE[,4]))/3)))
    
  return(A[,c( "series", "SMA_smape", "SMA_mase", "SMA_RelAvgRMSE")])
}





```


# 5.MAPA
 
```{r}

pred5 <- function(z,h,n){
  A <- data.frame( series = names(nn5),mapa_smape1 = NA_real_, mapa_mase1 = NA_real_, mapa_smape2 =
                     NA_real_, mapa_mase2 = NA_real_,
                  mapa_smape3 = NA_real_, mapa_mase3 = NA_real_, mapa_RMSE1 =NA_real_,mapa_RMSE2 = NA_real_,
                  mapa_RMSE3 = NA_real_, mapa_RelAvgRMSE = NA_real_)

#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
    fit <- mapa(x[[i]], ppy = 7, fh = h, comb = "mean", model = "ZZZ", paral = 2 ) 
    pred <- fit$outfor
    A[j,2*i] <- sMAPE(pred, x[[i+n]])
    A[j,2*i+1] <- MASE(pred, x[[i+n]], scale = df.mae[j,i+1])
    A[j,2*n+1+i] <- RMSE(pred, x[[i+n]])
    }
    
  }
  
  A <- mutate(group_by(A, series), mapa_smape = (( mapa_smape1 + mapa_smape2 + mapa_smape3)/3))
  A <- mutate(group_by(A, series), mapa_mase = (( mapa_mase1 + mapa_mase2 + mapa_mase3)/3)) # mean as
#  representer
  A[(1:111),11] <- ((RelAvgRMSE(A["mapa_RMSE1"],df.RMSE[,2]) + (RelAvgRMSE((A["mapa_RMSE2"]), df.RMSE[,3]) +
                                                 (RelAvgRMSE((A["mapa_RMSE3"]), df.RMSE[,4]))/3)))
    
  return(A[,c( "series", "mapa_smape", "mapa_mase", "mapa_RelAvgRMSE")])
}






```


# 6. Temporal Hierarchy


```{r}

pred6 <- function(z,h,n){
  A <- data.frame( series = names(nn5),thief_smape1 = NA_real_, thief_mase1 = NA_real_, thief_smape2 =
                     NA_real_, thief_mase2 = NA_real_,
                  thief_smape3 = NA_real_, thief_mase3 = NA_real_, thief_RMSE1 =NA_real_,thief_RMSE2 =
                    NA_real_, thief_RMSE3 = NA_real_, thief_RelAvgRMSE = NA_real_)

#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
    fit <- thief(x[[i]], m = 7, h = h, comb = "struc", usemodel = "theta") 
    A[j,2*i] <- sMAPE(fit$mean, x[[i+n]])
    A[j,2*i+1] <- MASE(fit$mean, x[[i+n]], scale = df.mae[j,i+1])
    A[j,2*n+1+i] <- RMSE(fit$mean, x[[i+n]])
    }
    
  }
  
  A <- mutate(group_by(A, series), thief_smape = (( thief_smape1 + thief_smape2 + thief_smape3)/3))
  A <- mutate(group_by(A, series), thief_mase = (( thief_mase1 + thief_mase2 + thief_mase3)/3)) # mean as
# representer
  A[(1:111),11] <- ((RelAvgRMSE(A["thief_RMSE1"],df.RMSE[,2]) + (RelAvgRMSE((A["thief_RMSE2"]), df.RMSE[,3])
                        + (RelAvgRMSE((A["thief_RMSE3"]), df.RMSE[,4]))/3)))
  return(A[,c( "series", "thief_smape", "thief_mase", "thief_RelAvgRMSE")])
}



```

# 7. TBATS

```{r}
# we need msts for this part

pred7 <- function(z,h,n){
  A <- data.frame( series = names(nn5),TBATS_smape1 = NA_real_, TBATS_mase1 = NA_real_, TBATS_smape2 =
                     NA_real_, TBATS_mase2 = NA_real_,
                  TBATS_smape3 = NA_real_, TBATS_mase3 = NA_real_, TBATS_RMSE1
                  =NA_real_,TBATS_RMSE2 =
                    NA_real_, TBATS_RMSE3 = NA_real_, TBATS_RelAvgRMSE = NA_real_)

#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
    fit <- tbats(x[[i]],use.arma.errors = T, use.trend = NULL, use.damped.trend = NULL, 
                 use.parallel = T, num.cores = 2) 
    pred <- forecast(fit, h = h)$mean
    A[j,2*i] <- sMAPE(pred, x[[i+n]])
    A[j,2*i+1] <- MASE(pred, x[[i+n]], scale = df.mae[j,i+1])
    A[j,2*n+1+i] <- RMSE(pred, x[[i+n]])
    }
    
  }
  
  A <- mutate(group_by(A, series), TBATS_smape = (( TBATS_smape1 + TBATS_smape2 + TBATS_smape3)/3))
  A <- mutate(group_by(A, series), TBATS_mase = (( TBATS_mase1 + TBATS_mase2 + TBATS_mase3)/3)) # mean as
# representer
  A[(1:111),11] <- ((RelAvgRMSE(A["TBATS_RMSE1"],df.RMSE[,2]) + (RelAvgRMSE((A["TBATS_RMSE2"]), df.RMSE[,3])
                        + (RelAvgRMSE((A["TBATS_RMSE3"]), df.RMSE[,4]))/3)))
  return(A[,c( "series", "TBATS_smape", "TBATS_mase", "TBATS_RelAvgRMSE")])
}





```


# 8. Neural Network

```{r}

pred8 <- function(z,h,n){
  A <- data.frame( series = names(nn5),nnet_smape1 = NA_real_, nnet_mase1 = NA_real_, nnet_smape2 =
                     NA_real_, nnet_mase2 = NA_real_,
                  nnet_smape3 = NA_real_, nnet_mase3 = NA_real_, nnet_RMSE1 =NA_real_,nnet_RMSE2 =
                    NA_real_, nnet_RMSE3 = NA_real_, nnet_RelAvgRMSE = NA_real_)

#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
    fit <- nnetar(x[[i]]) 
    pred <- forecast(fit, h = h)$mean 
    A[j,2*i] <- sMAPE(pred, x[[i+n]])
    A[j,2*i+1] <- MASE(pred, x[[i+n]], scale = df.mae[j,i+1])
    A[j,2*n+1+i] <- RMSE(pred, x[[i+n]])
    }
    
  }
  
  A <- mutate(group_by(A, series), nnet_smape = (( nnet_smape1 + nnet_smape2 + nnet_smape3)/3))
  A <- mutate(group_by(A, series), nnet_mase = (( nnet_mase1 + nnet_mase2 + nnet_mase3)/3)) # mean as
# representer
  A[(1:111),11] <- ((RelAvgRMSE(A["nnet_RMSE1"],df.RMSE[,2]) + (RelAvgRMSE((A["nnet_RMSE2"]), df.RMSE[,3])
                        + (RelAvgRMSE((A["nnet_RMSE3"]), df.RMSE[,4]))/3)))
  return(A[,c( "series", "nnet_smape", "nnet_mase", "nnet_RelAvgRMSE")])
}







```



#.9 ARIMA
```{r}

pred9 <- function(z,h,n){
  A <- data.frame( series = names(nn5),arima_smape1 = NA_real_, arima_mase1 = NA_real_, arima_smape2 =
                     NA_real_, arima_mase2 = NA_real_,
                  arima_smape3 = NA_real_, arima_mase3 = NA_real_, arima_RMSE1 =NA_real_,arima_RMSE2 =
                    NA_real_, arima_RMSE3 = NA_real_, arima_RelAvgRMSE = NA_real_)

#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
  
    fit <- auto.arima(x[[i]])
    pred <-forecast(fit, h = h)$mean
    A[j,2*i] <- sMAPE(pred, x[[i+n]])
    A[j,2*i+1] <- MASE(pred, x[[i+n]], scale = df.mae[j,i+1])
    A[j,2*n+1+i] <- RMSE(pred, x[[i+n]])
    }
    
  }
  
  A <- mutate(group_by(A, series), arima_smape = (( arima_smape1 + arima_smape2 + arima_smape3)/3))
  A <- mutate(group_by(A, series), arima_mase = (( arima_mase1 + arima_mase2 + arima_mase3)/3)) # mean as
# representer
  A[(1:111),11] <- ((RelAvgRMSE(A["arima_RMSE1"],df.RMSE[,2]) + (RelAvgRMSE((A["arima_RMSE2"]), df.RMSE[,3])
                        + (RelAvgRMSE((A["arima_RMSE3"]), df.RMSE[,4]))/3)))
  return(A[,c( "series", "arima_smape", "arima_mase", "arima_RelAvgRMSE")])
}


```


#10. Standard Theta 

```{r}


pred10 <- function(z,h,n){
  A <- data.frame( series = names(nn5),STheta_smape1 = NA_real_, STheta_mase1 = NA_real_, STheta_smape2 =
                     NA_real_, STheta_mase2 = NA_real_,
                  STheta_smape3 = NA_real_, STheta_mase3 = NA_real_, STheta_RMSE1 =NA_real_,STheta_RMSE2 =
                    NA_real_, STheta_RMSE3 = NA_real_, STheta_RelAvgRMSE = NA_real_)

#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
    fit <- stheta(x[[i]], h = h) 
    A[j,2*i] <- sMAPE(fit$mean, x[[i+n]])
    A[j,2*i+1] <- MASE(fit$mean, x[[i+n]], scale = df.mae[j,i+1])
    A[j,2*n+1+i] <- RMSE(fit$mean, x[[i+n]])
    }
    
  }
  
  A <- mutate(group_by(A, series), STheta_smape = (( STheta_smape1 + STheta_smape2 + STheta_smape3)/3))
  A <- mutate(group_by(A, series), STheta_mase = (( STheta_mase1 + STheta_mase2 + STheta_mase3)/3)) # mean as
# representer
  A[(1:111),11] <- ((RelAvgRMSE(A["STheta_RMSE1"],df.RMSE[,2]) + (RelAvgRMSE((A["STheta_RMSE2"]), df.RMSE[,3])
                        + (RelAvgRMSE((A["STheta_RMSE3"]), df.RMSE[,4]))/3)))
  return(A[,c( "series", "STheta_smape", "STheta_mase", "STheta_RelAvgRMSE")])
}




```


#11. Dynamic optimized theta method
```{r}
pred11 <- function(z,h,n){
  A <- data.frame( series = names(nn5),DOTM_smape1 = NA_real_, DOTM_mase1 = NA_real_, DOTM_smape2 =
                     NA_real_, DOTM_mase2 = NA_real_,
                  DOTM_smape3 = NA_real_, DOTM_mase3 = NA_real_, DOTM_RMSE1 =NA_real_,DOTM_RMSE2 =
                    NA_real_, DOTM_RMSE3 = NA_real_, DOTM_RelAvgRMSE = NA_real_)

#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
    fit <- dotm(x[[i]], h = h) 
    A[j,2*i] <- sMAPE(fit$mean, x[[i+n]])
    A[j,2*i+1] <- MASE(fit$mean, x[[i+n]], scale = df.mae[j,i+1])
    A[j,2*n+1+i] <- RMSE(fit$mean, x[[i+n]])
    }
    
  }
  
  A <- mutate(group_by(A, series), DOTM_smape = (( DOTM_smape1 + DOTM_smape2 + DOTM_smape3)/3))
  A <- mutate(group_by(A, series), DOTM_mase = (( DOTM_mase1 + DOTM_mase2 + DOTM_mase3)/3)) # mean as
# representer
  A[(1:111),11] <- ((RelAvgRMSE(A["DOTM_RMSE1"],df.RMSE[,2]) + (RelAvgRMSE((A["DOTM_RMSE2"]), df.RMSE[,3])
                        + (RelAvgRMSE((A["DOTM_RMSE3"]), df.RMSE[,4]))/3)))
  return(A[,c( "series", "DOTM_smape", "DOTM_mase", "DOTM_RelAvgRMSE")])
}



```


#12. CES
```{r}
pred12 <- function(z,h,n){
  A <- data.frame( series = names(nn5),CES_smape1 = NA_real_, CES_mase1 = NA_real_, CES_smape2 =
                     NA_real_, CES_mase2 = NA_real_,
                  CES_smape3 = NA_real_, CES_mase3 = NA_real_, CES_RMSE1 =NA_real_,CES_RMSE2 = NA_real_,
                  CES_RMSE3 = NA_real_, CES_RelAvgRMSE = NA_real_)

#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
    fit <- auto.ces(x[[i]],cfType = "MAE") 
    pred <- forecast(fit, h = h)
    A[j,2*i] <- sMAPE(pred$mean, x[[i+n]])
    A[j,2*i+1] <- MASE(pred$mean, x[[i+n]], scale = df.mae[j,i+1])
    A[j,2*n+1+i] <- RMSE(pred$mean, x[[i+n]])
    }
    
  }
  
  A <- mutate(group_by(A, series), CES_smape = (( CES_smape1 + CES_smape2 + CES_smape3)/3))
  A <- mutate(group_by(A, series), CES_mase = (( CES_mase1 + CES_mase2 + CES_mase3)/3)) # mean as representer
  A[(1:111),11] <- ((RelAvgRMSE(A["CES_RMSE1"],df.RMSE[,2]) + (RelAvgRMSE((A["CES_RMSE2"]), df.RMSE[,3]) +
                                                 (RelAvgRMSE((A["CES_RMSE3"]), df.RMSE[,4]))/3)))
    
  return(A[,c( "series", "CES_smape", "CES_mase", "CES_RelAvgRMSE")])
}


```


#13. Bagged ETS
```{r}

pred13 <- function(z,h,n){
  A <- data.frame( series = names(nn5),Bagged_ets_smape1 = NA_real_, Bagged_ets_mase1 = NA_real_,
                   Bagged_ets_smape2 = NA_real_, Bagged_ets_mase2 = NA_real_,
                   Bagged_ets_smape3 = NA_real_, Bagged_ets_mase3 = NA_real_, Bagged_ets_RMSE1
                   =NA_real_,Bagged_ets_RMSE2 = NA_real_,
                  Bagged_ets_RMSE3 = NA_real_, Bagged_ets_RelAvgRMSE = NA_real_)

#Rolling origin part
  for(j in seq_len(111)){
    x <- z[[j]]
    for(i in seq_len(n)){
#forecasting & Error parts
    fit <- baggedETS(x[[i]], bootstrapped_series = bld.mbb.bootstrap(x[[i]], 20), model = "ZZZ") 
    pred <- forecast(fit, h = h)
    A[j,2*i] <- sMAPE(pred$mean, x[[i+n]])
    A[j,2*i+1] <- MASE(pred$mean, x[[i+n]], scale = df.mae[j,i+1])
    A[j,2*n+1+i] <- RMSE(pred$mean, x[[i+n]])
    }
    
  }
  
  A <- mutate(group_by(A, series), Bagged_ets_smape = (( Bagged_ets_smape1 + Bagged_ets_smape2 +
                                                           Bagged_ets_smape3)/3))
  A <- mutate(group_by(A, series), Bagged_ets_mase = (( Bagged_ets_mase1 + Bagged_ets_mase2 +
                                                          Bagged_ets_mase3)/3)) # mean as representer
  A[(1:111),11] <- ((RelAvgRMSE(A["Bagged_ets_RMSE1"],df.RMSE[,2]) + (RelAvgRMSE((A["Bagged_ets_RMSE2"]),
                          df.RMSE[,3]) + (RelAvgRMSE((A["Bagged_ets_RMSE3"]), df.RMSE[,4]))/3)))
    
  return(A[,c( "series", "Bagged_ets_smape", "Bagged_ets_mase", "Bagged_ets_RelAvgRMSE")])
}

```


# computations - 12 step ahead

```{r}


newnn5 <- lapply(nn5,rolling_ori, h = 12, n = 3) # our new data :)
newnn5_35 <- lapply(nn5,rolling_ori, h = 35, n = 3)
newnn5_56  <- lapply(nn5,rolling_ori, h = 56, n = 3)

# tbats data
newnn5_t <- lapply(nn5,rolling_ori_msts, h = 12, n = 3) 
newnn5_35_t <- lapply(nn5,rolling_ori_msts, h = 35, n = 3)
newnn5_56_t <- lapply(nn5,rolling_ori_msts, h = 56, n = 3)

# first we are going to get the results for 12 step ahead


d2 <- pred2(newnn5,12,3)
result <- merge(result,d2[,c(1:3)]  ,by = "series")
df.mae <- d2[,c(1,4,5,6)]  # this little guy holds the key for future MASE computations!!
rm(d2)

d <- pred1(newnn5,12,3)
result <- merge(result, d[,c("series", "naive_smape", "naive_mase")], by = "series")
df.RMSE <- d[,c("series","RMSE1", "RMSE2", "RMSE3")]
rm(d)

d3 <- pred3(newnn5,12,3)
result <- merge(result,d3  ,by = "series")
rm(d3)


d4 <- pred4(newnn5,12,3)
result <- merge(result,d4  ,by = "series")
rm(d4)


d5 <- pred5(newnn5,12,3)
result <- merge(result,d5  ,by = "series")
rm(d5)

d6 <- pred6(newnn5,12,3)
result <- merge(result,d6  ,by = "series")
rm(d6)

d7 <- pred7(newnn5_t,12,3)
result <- merge(result,d7  ,by = "series")
rm(d7)

d8 <- pred8(newnn5,12,3)
result <- merge(result,d8  ,by = "series")
rm(d8)

d9 <- pred9(newnn5,12,3)
result <- merge(result,d9  ,by = "series")
rm(d9)

d10 <- pred10(newnn5,12,3)
result <- merge(result,d10  ,by = "series")
rm(d10)

d11 <- pred11(newnn5,12,3)
result <- merge(result,d11, by = "series")
rm(d11)

d12 <- pred12(newnn5,12,3)
result <- merge(result,d12  ,by = "series")
rm(d12)

d13 <- pred13(newnn5, 12,3)
result <- merge(result,d13  ,by = "series")
rm(d13, df.mae, df.RMSE)
```


# Computations - 35 step ahead

```{r}
d2 <- pred2(newnn5_35,35,3)
result_35 <- merge(result_35,d2[,c(1:3)]  ,by = "series")
df.mae <- d2[,c(1,4,5,6)]  # this little guy holds the key for future MASE computations!!
rm(d2)

d <- pred1(newnn5_35,35,3)
result_35 <- merge(result_35, d[,c("series", "naive_smape", "naive_mase")], by = "series")
df.RMSE <- d[,c("series","RMSE1", "RMSE2", "RMSE3")]
rm(d)

d3 <- pred3(newnn5_35,35,3)
result_35 <- merge(result_35,d3  ,by = "series")
rm(d3)

d4 <- pred4(newnn5_35,35,3)
result_35 <- merge(result_35,d4  ,by = "series")
rm(d4)

d5 <- pred5(newnn5_35,35,3)
result_35 <- merge(result_35,d5  ,by = "series")
rm(d5)

d6 <- pred6(newnn5_35,35,3)
result_35 <- merge(result_35,d6  ,by = "series")
rm(d6)

d7 <- pred7(newnn5_35_t,35,3)
result_35 <- merge(result_35,d7  ,by = "series")
rm(d7)

d8 <- pred8(newnn5_35,35,3)
result_35 <- merge(result_35,d8  ,by = "series")
rm(d8)

d9 <- pred9(newnn5_35,35,3)
result_35 <- merge(result_35,d9  ,by = "series")
rm(d9)

d10 <- pred10(newnn5_35,35,3)
result_35 <- merge(result_35,d10  ,by = "series")
rm(d10)

d11 <- pred11(newnn5_35,35,3)
result_35 <- merge(result_35,d11, by = "series")
rm(d11)

d12 <- pred12(newnn5_35,35,3)
result_35 <- merge(result_35,d12  ,by = "series")
rm(d12)

d13 <- pred13(newnn5_35, 35,3)
result <- merge(result,d13  ,by = "series")
rm(d13)

# renaming columns for more clarity

setnames(result_35, old = c("Snaive_smape", "Snaive_mase", "naive_smape", "naive_mase",
"ZZZ_smape", "ZZZ_mase", "ZZZ_RelAvgRMSE",
"SMA_smape", "SMA_mase", "SMA_RelAvgRMSE",
"mapa_smape", "mapa_mase", "mapa_RelAvgRMSE",
"thief_smape", "thief_mase", "thief_RelAvgRMSE",
"TBATS_smape", "TBATS_mase", "TBATS_RelAvgRMSE",
"nnet_smape", "nnet_mase", "nnet_RelAvgRMSE",
"arima_smape", "arima_mase", "arima_RelAvgRMSE",
"STheta_smape", "STheta_mase", "STheta_RelAvgRMSE",
"DOTM_smape", "DOTM_mase", "DOTM_RelAvgRMSE",
"CES_smape", "CES_mase", "CES_RelAvgRMSE",
"Bagged_ets_smape", "Bagged_ets_mase", "Bagged_ets_RelAvgRMSE"),
 new = c("Snaive_smape_35", "Snaive_mase_35" ,"naive_smape_35", "naive_mase_35",
"ZZZ_smape_35", "ZZZ_mase_35", "ZZZ_RelAvgRMSE_35",
"SMA_smape_35", "SMA_mase_35", "SMA_RelAvgRMSE_35",
"mapa_smape_35", "mapa_mase_35", "mapa_RelAvgRMSE_35",
"thief_smape_35", "thief_mase_35", "thief_RelAvgRMSE_35",
"TBATS_smape_35", "TBATS_mase_35", "TBATS_RelAvgRMSE_35",
"nnet_smape_35", "nnet_mase_35", "nnet_RelAvgRMSE_35",
"arima_smape_35", "arima_mase_35", "arima_RelAvgRMSE_35",
"STheta_smape_35", "STheta_mase_35", "STheta_RelAvgRMSE_35",
"DOTM_smape_35", "DOTM_mase_35", "DOTM_RelAvgRMSE_35",
"CES_smape_35", "CES_mase_35", "CES_RelAvgRMSE_35",
"Bagged_ets_smape_35", "Bagged_ets_mase_35", "Bagged_ets_RelAvgRMSE_35"))

```

# computation - 56 step ahead

```{r}
d2 <- pred2(newnn5_56,56,3)
result_56 <- merge(result_56,d2[,c(1:3)]  ,by = "series")
df.mae <- d2[,c(1,4,5,6)]  # this little guy holds the key for future MASE computations!!
rm(d2)

d <- pred1(newnn5_56,56,3)
result_56 <- merge(result_56, d[,c("series", "naive_smape", "naive_mase")], by = "series")
df.RMSE <- d[,c("series","RMSE1", "RMSE2", "RMSE3")]
rm(d)

d3 <- pred3(newnn5_56,56,3)
result_56 <- merge(result_56,d3  ,by = "series")
rm(d3)


d4 <- pred4(newnn5_56,56,3)
result_56 <- merge(result_56,d4  ,by = "series")
rm(d4)


d5 <- pred5(newnn5_56,56,3)
result_56 <- merge(result_56,d5  ,by = "series")
rm(d5)

d6 <- pred6(newnn5_56,56,3)
result_56 <- merge(result_56,d6  ,by = "series")
rm(d6)

d7 <- pred7(newnn5_56_t,56,3)
result_56 <- merge(result_56,d7  ,by = "series")
rm(d7)

d8 <- pred8(newnn5_56,56,3)
result_56 <- merge(result_56,d8  ,by = "series")
rm(d8)

d9 <- pred9(newnn5_56,56,3)
result_56 <- merge(result_56,d9  ,by = "series")
rm(d9)

d10 <- pred10(newnn5_56,56,3)
result_56 <- merge(result_56,d10  ,by = "series")
rm(d10)

d11 <- pred11(newnn5_56,56,3)
result_56 <- merge(result_56,d11, by = "series")
rm(d11)

d12 <- pred12(newnn5_56,56,3)
result_56 <- merge(result_56,d12  ,by = "series")

d13 <- pred13(newnn5_56, 56,3)
result <- merge(result,d13  ,by = "series")
rm(d12, d13, df.mae, df.RMSE)


setnames(result_56, old = c("Snaive_smape", "Snaive_mase", "naive_smape", "naive_mase",
"ZZZ_smape", "ZZZ_mase", "ZZZ_RelAvgRMSE",
"SMA_smape", "SMA_mase", "SMA_RelAvgRMSE",
"mapa_smape", "mapa_mase", "mapa_RelAvgRMSE",
"thief_smape", "thief_mase", "thief_RelAvgRMSE",
"TBATS_smape", "TBATS_mase", "TBATS_RelAvgRMSE",
"nnet_smape", "nnet_mase", "nnet_RelAvgRMSE",
"arima_smape", "arima_mase", "arima_RelAvgRMSE",
"STheta_smape", "STheta_mase", "STheta_RelAvgRMSE",
"DOTM_smape", "DOTM_mase", "DOTM_RelAvgRMSE",
"CES_smape", "CES_mase", "CES_RelAvgRMSE",
"Bagged_ets_smape", "Bagged_ets_mase", "Bagged_ets_RelAvgRMSE"),
 new = c("Snaive_smape_56", "Snaive_mase_56" ,"naive_smape_56", "naive_mase_56",
"ZZZ_smape_56", "ZZZ_mase_56", "ZZZ_RelAvgRMSE_56",
"SMA_smape_56", "SMA_mase_56", "SMA_RelAvgRMSE_56",
"mapa_smape_56", "mapa_mase_56", "mapa_RelAvgRMSE_56",
"thief_smape_56", "thief_mase_56", "thief_RelAvgRMSE_56",
"TBATS_smape_56", "TBATS_mase_56", "TBATS_RelAvgRMSE_56",
"nnet_smape_56", "nnet_mase_56", "nnet_RelAvgRMSE_56",
"arima_smape_56", "arima_mase_56", "arima_RelAvgRMSE_56",
"STheta_smape_56", "STheta_mase_56", "STheta_RelAvgRMSE_56",
"DOTM_smape_56", "DOTM_mase_56_56", "DOTM_RelAvgRMSE_56",
"CES_smape_56", "CES_mase_56", "CES_RelAvgRMSE_56",
"Bagged_ets_smape_56", "Bagged_ets_mase_56", "Bagged_ets_RelAvgRMSE_56"))
```





















```










